### ISSUE TITLE
Terminology loading is not working

### ISSUE THREAD

**Issue by rickskyy** [G-Node/python-odml#169]
During the testing process of loading and converting odml files with 
`<repository>http://portal.g-node.org/odml/terminologies/v1.0/terminologies.xml</repository>`
 
odml.tools.xmlparser.ParserException is raised like this:
`Failed to load http://portal.g-node.org/odml/terminologies/v1.0/terminologies.xml due to parser errors
 "Start tag expected, '<' not found, line 1, column 1"`

**Comment by jgrewe** [comment]
hey rickskyy, you are working with the master branch, respectively the future 1.4 version (1.1 model version), aren't you? then loading a 1.0  document will fail. We need to work on the error messages...

**Comment by mpsonntag** [comment]
It seems to be a problem when fetching and storing the file in question:

Python2 works fine; Python3 fails with exactly the above mentioned error message, since the downloaded file contains content marked as bytes. e.g.:

`b'<?xml version="1.0" encoding="ISO-8859-1"?>\n<?xml-stylesheet type="text/xsl" href="odmlRepository.xsl" xmlns:odml="http://www.g-node.org/odml"?>\n<odML version="1"> \n  ...'`

Either decode with python3 or find a way its already stored as "non-byte".

**Comment by mpsonntag** [comment]
Closed via [this commit](https://github.com/G-Node/python-odml/pull/198/commits/5e182f6b9fc04b6c4096075ba19e156d7461ee31).
