### ISSUE TITLE
Use inline style for rendering

### ISSUE THREAD

**Issue by sunfzjuelich** [G-Node/python-odml#331]
Dear Sie/Madame:

I am an employee at <a href="https://www.fz-juelich.de/inm/inm-6/EN/Home/home_node_INM6.html">INM-6, Forschungszentrum Jülich</a>. We use `odml` schema for data description.

I am writing to you to propose a method for rendering locally stored `odml` file, with inline style.

The problem is, locally stored `odml` files can not be rendered properly any more in new version of common browser softwares with the external `odml.xsl`. However they can be rendered using inline style. I tested it and it works fine.

The inline style sheet integration can be done like:

```
<?xml version="1.0" encoding="UTF-8"?>
<?xml-stylesheet type="text/xsl" href="#stylesheet"?>
<!DOCTYPE odML
[
	<!ATTLIST xsl:stylesheet
	id ID #REQUIRED>
]>
<odML version="1">
  <xsl:stylesheet id="stylesheet"
    version="1.0"
    xmlns:xsl="http://www.w3.org/1999/XSL/Transform" >
    <xsl:template match="odML">
      <xsl:variable name="repository" select="repository"/>
      <html>
        <!-- <head> //-->
          <style type="text/css">
            Here style sheets
          </style>
        <!-- </head> //-->
        <body>
          Here HTML body
        </body>
      </html>
    </xsl:template>
Followed by odml tags
```

This kind of inline styled `odml` files work directly in Firefox.
For Chrome `"application/xml"` must be registered in Mime-type database for `.odml` extension.

Best regards,
Sun

**Comment by morales-gregorio** [comment]
Hey all,

I was just discussing this issue with @sunfzjuelich, @JuliaSprenger and @mdenker beacuse it would be really cool to have a locally viewable file directly coming out from odml! 

A solution similar to the way @sunfzjuelich integrated the stylesheet in odml would be perfect for me, since I am working on a data publication that is in its final stages. It would be really helpful to have odml metadata to be viewable in any browser for the publication. It would make odml so much more useful for our target audience (who are potentially windows/mac based and not too keen on python).

All best,
Aitor

**Comment by mpsonntag** [comment]
@sunfzjuelich, @morales-gregorio, I just finished implementing a prototype but am still working out the kinks. I'll try to release a version until the end of the week.

**Comment by morales-gregorio** [comment]
Sounds awesome! :)

**Comment by mpsonntag** [comment]
@sunfzjuelich @morales-gregorio I just released a new odml version on PyPI containing the inline style option.

**Comment by morales-gregorio** [comment]
Just tried it and it works like a charm! From my side this solves the issue. 
Thanks a lot!

**Comment by sunfzjuelich** [comment]
OK, then I close this issue.

Thanks!
