### ISSUE TITLE
documentation minor tweak

### ISSUE THREAD

**Issue by Vutsuak16** [G-Node/python-odml#61]
The following output is displayed in the docs which is wrong.
Instead of "Douglas Adams" it should have been "D.N Adams"
![capture](https://cloud.githubusercontent.com/assets/10365536/23007457/d22820ac-f42e-11e6-80bc-fe62e258f872.PNG)

Do you want me to do a PR?
There are few other improvements I found like:
![capture](https://cloud.githubusercontent.com/assets/10365536/23007543/60fa9364-f42f-11e6-9fc1-df962c13f748.PNG)

1.It should have been odmlEx.date instead of odmlfile
2. odmlEx.repository is an unnecessary command

**Comment by lzehl** [comment]
Hello @vutsuak16! 
Thanks for checking the documentation. 
I'm already updating the documentation for issue #58 and also noticed these errors. There are other changes in progress which require an update of the documentation. I'm currently just waiting for them to be merged so that I can work with one branch. I suggest we join forces! I would be happy about a second proof reader.

For your 2. point: repository is a command for all odML objects but it's not documented yet. It's on my list for the update.

**Comment by Vutsuak16** [comment]
Well sure @lzehl  we can work together on it.
I would notify of any other discrepancies.
When shall we proceed with the PRs?

**Comment by lzehl** [comment]
Great :) I've created on my fork a branch (updated_docu) from the current master in which I updated the tutorial.rst with the parts I had already. Let me know if you find more. I'm sure there is a lot to do, because so far the documentation is still based on my first draft after the first odml updates.
I really appreciate the help/second pair of eyes :) Thanks!

**Comment by lzehl** [comment]
@Vutsuak16 thanks again for checking the documentation! 
I think I took care of this with issue #97. 
Let me know if you find new bugs in the updated tutorial. 
@jgrewe I close this issue because it should be taken care off with issue #97
